/*
 / _____)             _              | |
( (____  _____ ____ _| |_ _____  ____| |__
 \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 _____) ) ____| | | || |_| ____( (___| | | |
(______/|_____)_|_|_| \__)_____)\____)_| |_|
    (C)2015 Semtech

Description: End device commissioning parameters

License: Revised BSD License, see LICENSE.TXT file include in the project

Maintainer: Miguel Luis and Gregory Cristian
*/
#ifndef __LORA_COMMISSIONING_H__
#define __LORA_COMMISSIONING_H__

/*!
 * When set to 1 the application uses the Over-the-Air activation procedure
 * When set to 0 the application uses the Personalization activation procedure
 */
#define OVER_THE_AIR_ACTIVATION                     1

/*!
 * Indicates if the end-device is to be connected to a private or public network
 */
#define LORAWAN_PUBLIC_NETWORK                      true

/*!
 * IEEE Organizationally Unique Identifier ( OUI ) (big endian)
 * \remark This is unique to a company or organization
 */
//#define IEEE_OUI                                    0x00, 0x00, 0x00

/*!
 * Mote device IEEE EUI (big endian)
 *
 * \remark In this application the value is automatically generated by calling
 *         BoardGetUniqueId function
 */

//XRange 2
//Sur TTN
#define  LORAWAN_DEVICE_EUI {0x05,0x00,0xFA,0xFF,0x71,0x62,0x8E,0x9D}
//Sur SPOT 0500FAFF71628E9E
//#define  LORAWAN_DEVICE_EUI {0x05,0x00,0xFA,0xFF,0x71,0x62,0x8E,0x9E}
// 70B3D57EF00049E1
#define  LORAWAN_APPLICATION_EUI {0x70,0xB3,0xD5,0x7E,0xF0,0x00,0x49,0xE1};
//58A803F6D4AAE147386129664869CC23
#define  LORAWAN_APPLICATION_KEY {0x58,0xA8,0x03,0xF6,0xD4,0xAA,0xE1,0x47,0x38,0x61,0x29,0x66,0x48,0x69,0xCC,0x23};



//DevEUI XRange_3 pour spot
//#define LORAWAN_DEVICE_EUI                          { 0x0B, 0x00, 0xF4, 0xFF, 0x6F, 0x3E, 0x90, 0xC1 }

//DevEUI XRange_3 pour TTN
//#define LORAWAN_DEVICE_EUI                          { 0x0B, 0x00, 0xF4, 0xFF, 0x6F, 0x3E, 0x90, 0xC2 }

//#define LORAWAN_DEVICE_EUI                          { IEEE_OUI, 0x00, 0x00, 0x00, 0x00, 0x00 }

/*!
 * Application IEEE EUI (big endian)
 */
//#define LORAWAN_APPLICATION_EUI                     { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }
//#define LORAWAN_APPLICATION_EUI                     { 0x70, 0xB3, 0xD5, 0x7E, 0xF0, 0x00, 0x49, 0xE1 }

/*!
 * AES encryption/decryption cipher application key
 */
//#define LORAWAN_APPLICATION_KEY                     { 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }

//#define LORAWAN_APPLICATION_KEY   { 0x30, 0x4C, 0x99, 0x26, 0x3E, 0xA5, 0xE6, 0x43, 0xB5, 0xA0, 0x8C, 0xB3, 0x25, 0x4A, 0x61, 0xFA }

/*!
 * Current network ID
 */
#define LORAWAN_NETWORK_ID                          ( uint32_t )0

/*!
 * Device address on the network (big endian)
 *
 * \remark In this application the value is automatically generated using
 *         a pseudo random generator seeded with a value derived from
 *         BoardUniqueId value if LORAWAN_DEVICE_ADDRESS is set to 0
 */
#define LORAWAN_DEVICE_ADDRESS                      ( uint32_t )0x00000000

/*!
 * AES encryption/decryption cipher network session key
 */
#define LORAWAN_NWKSKEY                             { 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }

/*!
 * AES encryption/decryption cipher application session key
 */
#define LORAWAN_APPSKEY                             { 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }

#endif // __LORA_COMMISSIONING_H__
